apiVersion: v1
kind: ConfigMap
metadata:
  name: pegasus-config
  namespace: pegasus
data:
  PEGASUS_VALIDATION_DISTRIBUTED_ENABLED: "true"
  PEGASUS_VALIDATION_REDIS_URL: "redis://pegasus-redis:6379/0"
  PEGASUS_VALIDATION_WORK_DIR: "/data/pegasus/work"
  PEGASUS_VALIDATION_PARTITION_RECONCILE_WORKERS: "0"
  PEGASUS_VALIDATION_RECONCILIATION_PARTITION_WAVE_SIZE: "64"
  REDIS_URL: "redis://pegasus-redis:6379/0"
