apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pegasus-ingress
  namespace: pegasus
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
    - host: pegasus.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pegasus-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pegasus-frontend
                port:
                  number: 80
