apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: category1-ingress
  namespace: category1
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
    - host: category1.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: category1-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: category1-frontend
                port:
                  number: 80
